### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Move-Dance-Feel#22]
Are we happy to using CSS? I never asked if anyone wants to use SASS

I think CSS would be easier though but I understand if people wont to learn something new. Plus would be helpful for covering different browsers compatibility.  

If we use SASS, I think we should do it along these lines https://webdesign.tutsplus.com/tutorials/watch-and-compile-sass-in-five-quick-steps--cms-28275
with a command that compiles the SASS files as a part of the deployment so we don't need to have issues with conflicting CSS files.

**Comment by ahmedisam99** [comment]
Well, I believe we won't be needing SASS and it's gonna talk a while to learn and use.

I prefer we stay at CSS
