### ISSUE TITLE
fix font-family and font sizes across website

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Move-Dance-Feel#55]
The Quentin font seems really hard to read at times, using it more sparingly, font-weight: 550, Kite one for the rest af the text.

**Comment by Dalmano** [comment]
font size for the rest of the text?

**Comment by dubhcait** [comment]
right now it's 25px for normal p, Im looking at 18 far smaller things

**Comment by dubhcait** [comment]
I need to do some adjusting for smaller screens next
