### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Move-Dance-Feel#6]
Please add any options you would like to do, you can edit this issue and we can comment on this issue to vote

## Stack 
- React and express backend 
- React serverless (using netlify functions) 
- gatsby https://www.gatsbyjs.org/
- serverside rendering with express or hapi https://hapi.dev/ combiened with a templating engine like handlebars or https://pugjs.org/api/express.html 

## Testing 
- Tape
- Jest (+/- enzyme https://github.com/airbnb/enzyme )
-  Cypress https://www.cypress.io/

## Naming Branches

Branch naming follows this convention ( issue number-description )
E.g. 12-note-page or 15-fix-searchBar

or 

Feature , Fix , Test convention
E.g. feature/note-page, fix/note-page , test/searchBar

**Comment by dubhcait** [comment]
Stack: I want to try a different stack to the first option ie React and express backend, I like the idea of doing server-side rendering but unless everyone wants to build it that way I think we should go with a different option.

Testing: I want to try Cypress

Naming Branches: I like directly linking the names to the issues they resolve

**Comment by Dalmano** [comment]
I'm up for trying something different so happy to try server-side rendering.

For naming branches I think option 1 works best, just in terms of clarity and relating to a specific issue number

**Comment by naremanhilles** [comment]
I like use React in front and use react library we can use ant design or react-bootstrap i prefer react-bootstrap more than ant,in back express.
I think  we didn't need test all pages will be static unless nodemailer 
Naming Branches: I like directly linking the names to the issues they resolve so option

**Comment by ahmedisam99** [comment]
I don't mind using SSR as `hbs` is our template engine.
For the testing, I prefer using `tape` because of its simplicity.
Branch naming: shall follow `issueNumber-issue-desc`

**Comment by dubhcait** [comment]
With @naremanhilles preferring to use react I think we should go with react, I think we would all need to be on board for SSR to work. It was an option but maybe not the best considering our project. 

We can use react, I've never used bootstrap but I'm up for it.  I think all we would be using the express server is for nodemailer.

How about a serverless build? like this project https://github.com/FAC-Sixteen/square-circle, they used sendmail instead of nodemailer ( as the need the same functionality in sending emails to the website owner).  They also needed extra functionality from a database ( so they used Airtable) but we don't need that.

**Comment by naremanhilles** [comment]
Don't worry ant and react bootstrap verey easy I can help you to understand how using thes libraray but I prefer using nodemailer because I want learn nodemailer and I didn't use it?

**Comment by naremanhilles** [comment]
Don't worry ant and react bootstrap verey easy I can help you to understand how using thes libraray but I prefer using nodemailer because I want learn nodemailer and I didn't use it?

**Comment by naremanhilles** [comment]
Yes I can help you kait to know how use this library so ant and react-bootstrap verey easy but I prefer use nodemailer because I didn't used before and I want learn nodemailer?

**Comment by dubhcait** [comment]
I've used nodemaier a lot. It's very useful but not actually that much learning. If you want I can help you make a demo but it does have the problem of maintainability. It needs an email address and password to function properly so if our PO changes the password then it breaks. Where as sendmail hasn't the maintainability problems but has other issue.

**Comment by naremanhilles** [comment]
Ok we can use sendmail
